name: restapi
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - uvicorn
  - pandas
  - fastapi
  - dash
  - conda-forge::dash-bootstrap-components
  - conda-forge::dash-daq
#prefix: /Users/SebasPenaherrera/anaconda3/envs/restapi
