# Dockerfile for Video360_WebUI image
# This image is based on Ubuntu 20.04 and contains all the necessary packages to run the Video360_WebUI project including the conda environment, ssh server, REST server and the web server
# The image exposes the ports 30000-40000 for the REST server and the web server
# The image also exposes the port 22 for ssh access
# Author: Sebastian Peñaherrera
# Date: 2024-05-10
# Version: 2.0

FROM ubuntu:latest

EXPOSE 30000-40000

# LINUX PACKAGES ----------------------------------------------------------------------------------------------------------------------------
RUN apt-get update && apt-get install wget -y
RUN apt-get install tmux -y 
RUN apt-get install git -y
RUN cd /opt/ && git clone -c http.sslverify=False https://sppulla:Sebas4080@192.168.159.150:3000/sppulla/Video360_WebUI.git

# Avoid cache and update repo
ADD "https://www.random.org/cgi-bin/randbyte?nbytes=10&format=h" skipcache
WORKDIR /opt/Video360_WebUI/
RUN git pull

# CONFIGURE SSH -----------------------------------------------------------------------------------------------------------------------------
RUN apt-get install openssh-server -y

RUN mkdir /var/run/sshd
RUN echo 'root:mobilenet131' | chpasswd
RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
EXPOSE 22

# CONFIGURE CONDA ---------------------------------------------------------------------------------------------------------------------------
RUN mkdir -p /opt/conda
RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O /opt/conda/miniconda.sh
RUN chmod +x /opt/conda/miniconda.sh 
RUN /opt/conda/miniconda.sh -b -p /opt/miniconda 

RUN cp /opt/Video360_WebUI/environment.yml /tmp/
# Add CONDA path to the environments paths
RUN export CONDA=/opt/miniconda/ && export PATH=$PATH:/opt/miniconda/bin && conda init
# Activate Conda 
RUN . /opt/miniconda/bin/activate && conda update conda -y && conda env create --file /tmp/environment.yml

# DEFAULT CONTAINER COMMAND ------------------------------------------------------------------------------------------------------------------
RUN chmod +x /opt/Video360_WebUI/run.sh
#CMD ["/usr/sbin/sshd", "-D"]
CMD ["/opt/Video360_WebUI/run.sh"]